spring.application.name=auth-service
server.port=8081
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=auth_service;encrypt=true;trustServerCertificate=true
spring.datasource.username=nikhil
spring.datasource.password=nikhil
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver