spring.application.name=discovery-server
# Give the server a port
server.port=8761

# Tell the server not to register itself with the registry
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
